version: '3.8'

services:
  mycg-ai-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/venv
      - ./temp_uploads:/app/temp_uploads
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - mycg-dev-network
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - mycg-dev-network
    volumes:
      - redis_dev_data:/data

networks:
  mycg-dev-network:
    driver: bridge

volumes:
  redis_dev_data: